// Copyright (C) 2015-2026 The Neo Project.
//
// NeoVmToRustTranslator.cs file belongs to the neo project and is free
// software distributed under the MIT software license, see the
// accompanying file LICENSE in the main directory of the
// repository or http://www.opensource.org/licenses/mit-license.php
// for more details.
//
// Redistribution and use in source and binary forms with or without
// modifications are permitted.

using Neo.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;

namespace Neo.Compiler.Backend.RiscV
{
    /// <summary>
    /// Translates NeoVM bytecode instructions to Rust source code for RISC-V target.
    /// </summary>
    public class NeoVmToRustTranslator
    {
        private readonly StringBuilder _output;
        private readonly string _contractName;
        private int _indentLevel;
        private int _labelCounter;
        private readonly Dictionary<int, string> _offsetLabels;
        private readonly Dictionary<string, int> _methodOffsets;

        public NeoVmToRustTranslator(string contractName)
        {
            _output = new StringBuilder();
            _contractName = contractName;
            _indentLevel = 0;
            _labelCounter = 0;
            _offsetLabels = new Dictionary<int, string>();
            _methodOffsets = new Dictionary<string, int>();
        }

        /// <summary>
        /// Translates a collection of NeoVM instructions to Rust source code.
        /// </summary>
        public string Translate(IEnumerable<Instruction> instructions, Dictionary<string, int>? methodOffsets = null)
        {
            if (methodOffsets != null)
            {
                _methodOffsets.Clear();
                foreach (var kvp in methodOffsets)
                {
                    _methodOffsets[kvp.Key] = kvp.Value;
                }
            }

            // Generate labels for jump targets
            GenerateLabels(instructions);

            // Write header
            WriteHeader();

            // Write contract struct and methods
            WriteContractImplementation(instructions);

            // Write footer
            WriteFooter();

            return _output.ToString();
        }

        private void GenerateLabels(IEnumerable<Instruction> instructions)
        {
            foreach (var instruction in instructions)
            {
                if (instruction.Target != null && instruction.Target.Instruction != null)
                {
                    int targetOffset = instruction.Target.Instruction.Offset;
                    if (!_offsetLabels.ContainsKey(targetOffset))
                    {
                        _offsetLabels[targetOffset] = $"label_{targetOffset:x4}";
                    }
                }
                if (instruction.Target2 != null && instruction.Target2.Instruction != null)
                {
                    int targetOffset = instruction.Target2.Instruction.Offset;
                    if (!_offsetLabels.ContainsKey(targetOffset))
                    {
                        _offsetLabels[targetOffset] = $"label_{targetOffset:x4}";
                    }
                }
            }
        }

        private void WriteHeader()
        {
            WriteLine("// Auto-generated Rust code for RISC-V target from NeoVM bytecode");
            WriteLine("// This file is generated by Neo.Compiler.CSharp");
            WriteLine();
            WriteLine("#![no_std]");
            WriteLine("#![no_main]");
            WriteLine();
            WriteLine("use neo_riscv_devpack::*;");
            WriteLine("use neo_riscv_devpack::syscalls::*;");
            WriteLine("use neo_riscv_devpack::types::*;");
            WriteLine();
        }

        private void WriteContractImplementation(IEnumerable<Instruction> instructions)
        {");
            WriteLine();
            WriteLine($"pub struct {_contractName};");
            WriteLine();
            WriteLine($"impl {_contractName} {{");
            _indentLevel++;

            // Write methods based on method offsets
            if (_methodOffsets.Count > 0)
            {
                foreach (var methodEntry in _methodOffsets.OrderBy(m => m.Value))
                {
                    WriteMethod(methodEntry.Key, instructions, methodEntry.Value);
                }
            }
            else
            {
                // Single main method if no method offsets provided
                WriteMethod("main", instructions, 0);
            }

            _indentLevel--;
            WriteLine("}");
        }

        private void WriteMethod(string methodName, IEnumerable<Instruction> instructions, int startOffset)
        {
            WriteLine();
            WriteLine($"pub fn {methodName}() -> Result<StackItem, ContractError> {{");
            _indentLevel++;

            // Initialize VM state
            WriteLine("// Initialize evaluation stack");
            WriteLine("let mut stack: Vec<StackItem> = Vec::new();");
            WriteLine("let mut alt_stack: Vec<StackItem> = Vec::new();");
            WriteLine("let mut static_fields: Vec<StackItem> = Vec::new();");
            WriteLine("let mut local_vars: Vec<StackItem> = Vec::new();");
            WriteLine("let mut args: Vec<StackItem> = Vec::new();");
            WriteLine();

            // Get instructions for this method
            var methodInstructions = instructions.ToList();
            int endOffset = GetMethodEndOffset(startOffset, methodInstructions);

            // Translate instructions
            foreach (var instruction in methodInstructions)
            {
                if (instruction.Offset < startOffset) continue;
                if (endOffset > 0 && instruction.Offset >= endOffset) break;

                // Write label if this offset has one
                if (_offsetLabels.TryGetValue(instruction.Offset, out string? label))
                {
                    _indentLevel--;
                    WriteLine($"{label}:");
                    _indentLevel++;
                }

                TranslateInstruction(instruction);
            }

            // Return result
            WriteLine();
            WriteLine("// Return top of stack or null");
            WriteLine("Ok(stack.pop().unwrap_or(StackItem::Null))");

            _indentLevel--;
            WriteLine("}");
        }

        private int GetMethodEndOffset(int startOffset, List<Instruction> instructions)
        {
            // Find the next method offset
            var nextMethod = _methodOffsets
                .Where(m => m.Value > startOffset)
                .OrderBy(m => m.Value)
                .FirstOrDefault();

            return nextMethod.Value > 0 ? nextMethod.Value : -1;
        }

        private void TranslateInstruction(Instruction instruction)
        {
            WriteLine($"// {instruction.OpCode} at offset {instruction.Offset:x4}");

            switch (instruction.OpCode)
            {
                // Constants
                case OpCode.PUSHINT8:
                case OpCode.PUSHINT16:
                case OpCode.PUSHINT32:
                case OpCode.PUSHINT64:
                case OpCode.PUSHINT128:
                case OpCode.PUSHINT256:
                    PushInteger(instruction);
                    break;

                case OpCode.PUSHT:
                    WriteLine("stack.push(StackItem::Boolean(true));");
                    break;

                case OpCode.PUSHF:
                    WriteLine("stack.push(StackItem::Boolean(false));");
                    break;

                case OpCode.PUSHNULL:
                    WriteLine("stack.push(StackItem::Null);");
                    break;

                case OpCode.PUSHDATA1:
                case OpCode.PUSHDATA2:
                case OpCode.PUSHDATA4:
                    PushData(instruction);
                    break;

                case OpCode.PUSHM1:
                    WriteLine("stack.push(StackItem::Integer(BigInt::from(-1i32)));");
                    break;

                case OpCode.PUSH0:
                case OpCode.PUSH1:
                case OpCode.PUSH2:
                case OpCode.PUSH3:
                case OpCode.PUSH4:
                case OpCode.PUSH5:
                case OpCode.PUSH6:
                case OpCode.PUSH7:
                case OpCode.PUSH8:
                case OpCode.PUSH9:
                case OpCode.PUSH10:
                case OpCode.PUSH11:
                case OpCode.PUSH12:
                case OpCode.PUSH13:
                case OpCode.PUSH14:
                case OpCode.PUSH15:
                case OpCode.PUSH16:
                    int value = instruction.OpCode - OpCode.PUSH0;
                    WriteLine($"stack.push(StackItem::Integer(BigInt::from({value}i32)));");
                    break;

                // Flow control
                case OpCode.NOP:
                    WriteLine("// NOP");
                    break;

                case OpCode.JMP:
                case OpCode.JMP_L:
                    Jump(instruction);
                    break;

                case OpCode.JMPIF:
                case OpCode.JMPIF_L:
                    ConditionalJump(instruction, true);
                    break;

                case OpCode.JMPIFNOT:
                case OpCode.JMPIFNOT_L:
                    ConditionalJump(instruction, false);
                    break;

                case OpCode.CALL:
                case OpCode.CALL_L:
                    Call(instruction);
                    break;

                case OpCode.RET:
                    WriteLine("return Ok(stack.pop().unwrap_or(StackItem::Null));");
                    break;

                case OpCode.SYSCALL:
                    Syscall(instruction);
                    break;

                // Stack operations
                case OpCode.DROP:
                    WriteLine("let _ = stack.pop();");
                    break;

                case OpCode.DUP:
                    WriteLine("let top = stack.last().cloned().unwrap_or(StackItem::Null);");
                    WriteLine("stack.push(top);");
                    break;

                case OpCode.SWAP:
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("stack.push(a);");
                    WriteLine("stack.push(b);");
                    break;

                case OpCode.PICK:
                    WriteLine("let n = stack.pop().unwrap_or(StackItem::Null).to_int() as usize;");
                    WriteLine("let item = stack.get(stack.len() - 1 - n).cloned().unwrap_or(StackItem::Null);");
                    WriteLine("stack.push(item);");
                    break;

                case OpCode.ROLL:
                    WriteLine("let n = stack.pop().unwrap_or(StackItem::Null).to_int() as usize;");
                    WriteLine("let idx = stack.len() - 1 - n;");
                    WriteLine("let item = stack.remove(idx);");
                    WriteLine("stack.push(item);");
                    break;

                // Slot operations
                case OpCode.LDSFLD0:
                case OpCode.LDSFLD1:
                case OpCode.LDSFLD2:
                case OpCode.LDSFLD3:
                case OpCode.LDSFLD4:
                case OpCode.LDSFLD5:
                case OpCode.LDSFLD6:
                    int sfldIdx = instruction.OpCode - OpCode.LDSFLD0;
                    WriteLine($"stack.push(static_fields.get({sfldIdx}).cloned().unwrap_or(StackItem::Null));");
                    break;

                case OpCode.LDSFLD:
                    int sfldIndex = instruction.Operand?[0] ?? 0;
                    WriteLine($"stack.push(static_fields.get({sfldIndex}).cloned().unwrap_or(StackItem::Null));");
                    break;

                case OpCode.STSFLD0:
                case OpCode.STSFLD1:
                case OpCode.STSFLD2:
                case OpCode.STSFLD3:
                case OpCode.STSFLD4:
                case OpCode.STSFLD5:
                case OpCode.STSFLD6:
                    int stsfldIdx = instruction.OpCode - OpCode.STSFLD0;
                    WriteLine($"if static_fields.len() <= {stsfldIdx} {{ static_fields.resize({stsfldIdx} + 1, StackItem::Null); }}");
                    WriteLine($"static_fields[{stsfldIdx}] = stack.pop().unwrap_or(StackItem::Null);");
                    break;

                case OpCode.STSFLD:
                    int stsfldIndex = instruction.Operand?[0] ?? 0;
                    WriteLine($"if static_fields.len() <= {stsfldIndex} {{ static_fields.resize({stsfldIndex} + 1, StackItem::Null); }}");
                    WriteLine($"static_fields[{stsfldIndex}] = stack.pop().unwrap_or(StackItem::Null);");
                    break;

                case OpCode.LDLOC0:
                case OpCode.LDLOC1:
                case OpCode.LDLOC2:
                case OpCode.LDLOC3:
                case OpCode.LDLOC4:
                case OpCode.LDLOC5:
                case OpCode.LDLOC6:
                    int locIdx = instruction.OpCode - OpCode.LDLOC0;
                    WriteLine($"stack.push(local_vars.get({locIdx}).cloned().unwrap_or(StackItem::Null));");
                    break;

                case OpCode.LDLOC:
                    int locIndex = instruction.Operand?[0] ?? 0;
                    WriteLine($"stack.push(local_vars.get({locIndex}).cloned().unwrap_or(StackItem::Null));");
                    break;

                case OpCode.STLOC0:
                case OpCode.STLOC1:
                case OpCode.STLOC2:
                case OpCode.STLOC3:
                case OpCode.STLOC4:
                case OpCode.STLOC5:
                case OpCode.STLOC6:
                    int stlocIdx = instruction.OpCode - OpCode.STLOC0;
                    WriteLine($"if local_vars.len() <= {stlocIdx} {{ local_vars.resize({stlocIdx} + 1, StackItem::Null); }}");
                    WriteLine($"local_vars[{stlocIdx}] = stack.pop().unwrap_or(StackItem::Null);");
                    break;

                case OpCode.STLOC:
                    int stlocIndex = instruction.Operand?[0] ?? 0;
                    WriteLine($"if local_vars.len() <= {stlocIndex} {{ local_vars.resize({stlocIndex} + 1, StackItem::Null); }}");
                    WriteLine($"local_vars[{stlocIndex}] = stack.pop().unwrap_or(StackItem::Null);");
                    break;

                case OpCode.LDARG0:
                case OpCode.LDARG1:
                case OpCode.LDARG2:
                case OpCode.LDARG3:
                case OpCode.LDARG4:
                case OpCode.LDARG5:
                case OpCode.LDARG6:
                    int argIdx = instruction.OpCode - OpCode.LDARG0;
                    WriteLine($"stack.push(args.get({argIdx}).cloned().unwrap_or(StackItem::Null));");
                    break;

                case OpCode.LDARG:
                    int argIndex = instruction.Operand?[0] ?? 0;
                    WriteLine($"stack.push(args.get({argIndex}).cloned().unwrap_or(StackItem::Null));");
                    break;

                case OpCode.STARG0:
                case OpCode.STARG1:
                case OpCode.STARG2:
                case OpCode.STARG3:
                case OpCode.STARG4:
                case OpCode.STARG5:
                case OpCode.STARG6:
                    int stargIdx = instruction.OpCode - OpCode.STARG0;
                    WriteLine($"if args.len() <= {stargIdx} {{ args.resize({stargIdx} + 1, StackItem::Null); }}");
                    WriteLine($"args[{stargIdx}] = stack.pop().unwrap_or(StackItem::Null);");
                    break;

                case OpCode.STARG:
                    int stargIndex = instruction.Operand?[0] ?? 0;
                    WriteLine($"if args.len() <= {stargIndex} {{ args.resize({stargIndex} + 1, StackItem::Null); }}");
                    WriteLine($"args[{stargIndex}] = stack.pop().unwrap_or(StackItem::Null);");
                    break;

                // Arithmetic
                case OpCode.ADD:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Integer(a + b));");
                    break;

                case OpCode.SUB:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Integer(a - b));");
                    break;

                case OpCode.MUL:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Integer(a * b));");
                    break;

                case OpCode.DIV:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("if b == BigInt::from(0) { return Err(ContractError::DivideByZero); }");
                    WriteLine("stack.push(StackItem::Integer(a / b));");
                    break;

                case OpCode.MOD:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("if b == BigInt::from(0) { return Err(ContractError::DivideByZero); }");
                    WriteLine("stack.push(StackItem::Integer(a % b));");
                    break;

                case OpCode.NEGATE:
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Integer(-a));");
                    break;

                case OpCode.ABS:
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Integer(if a < BigInt::from(0) { -a } else { a }));");
                    break;

                case OpCode.INC:
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Integer(a + BigInt::from(1)));");
                    break;

                case OpCode.DEC:
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Integer(a - BigInt::from(1)));");
                    break;

                // Comparison
                case OpCode.EQUAL:
                case OpCode.NUMEQUAL:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("stack.push(StackItem::Boolean(a == b));");
                    break;

                case OpCode.NOTEQUAL:
                case OpCode.NUMNOTEQUAL:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("stack.push(StackItem::Boolean(a != b));");
                    break;

                case OpCode.LT:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Boolean(a < b));");
                    break;

                case OpCode.LE:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Boolean(a <= b));");
                    break;

                case OpCode.GT:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Boolean(a > b));");
                    break;

                case OpCode.GE:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_int();");
                    WriteLine("stack.push(StackItem::Boolean(a >= b));");
                    break;

                // Logical
                case OpCode.AND:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("stack.push(StackItem::Boolean(a && b));");
                    break;

                case OpCode.OR:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("stack.push(StackItem::Boolean(a || b));");
                    break;

                case OpCode.NOT:
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("stack.push(StackItem::Boolean(!a));");
                    break;

                case OpCode.BOOLAND:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("stack.push(StackItem::Boolean(a && b));");
                    break;

                case OpCode.BOOLOR:
                    WriteLine("let b = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("stack.push(StackItem::Boolean(a || b));");
                    break;

                // Array/Map operations
                case OpCode.NEWARRAY0:
                    WriteLine("stack.push(StackItem::Array(Vec::new()));");
                    break;

                case OpCode.NEWARRAY:
                    WriteLine("let n = stack.pop().unwrap_or(StackItem::Null).to_int() as usize;");
                    WriteLine("let arr = vec![StackItem::Null; n];");
                    WriteLine("stack.push(StackItem::Array(arr));");
                    break;

                case OpCode.NEWMAP:
                    WriteLine("stack.push(StackItem::Map(Vec::new()));");
                    break;

                case OpCode.PACK:
                    WriteLine("let n = stack.pop().unwrap_or(StackItem::Null).to_int() as usize;");
                    WriteLine("let mut arr = Vec::with_capacity(n);");
                    WriteLine("for _ in 0..n { arr.push(stack.pop().unwrap_or(StackItem::Null)); }");
                    WriteLine("arr.reverse();");
                    WriteLine("stack.push(StackItem::Array(arr));");
                    break;

                case OpCode.UNPACK:
                    WriteLine("let arr = match stack.pop().unwrap_or(StackItem::Null) {");
                    WriteLine("    StackItem::Array(a) => a,");
                    WriteLine("    _ => return Err(ContractError::InvalidType),");
                    WriteLine("};");
                    WriteLine("let len = arr.len();");
                    WriteLine("for item in arr.into_iter().rev() { stack.push(item); }");
                    WriteLine("stack.push(StackItem::Integer(BigInt::from(len)));");
                    break;

                case OpCode.PICKITEM:
                    WriteLine("let key = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let collection = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let value = collection.get_item(&key)?;");
                    WriteLine("stack.push(value);");
                    break;

                case OpCode.SETITEM:
                    WriteLine("let value = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let key = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let collection = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("collection.set_item(key, value)?;");
                    break;

                case OpCode.SIZE:
                    WriteLine("let item = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let size = item.size()?;");
                    WriteLine("stack.push(StackItem::Integer(BigInt::from(size)));");
                    break;

                case OpCode.CLEAR:
                    WriteLine("stack.clear();");
                    break;

                // Type operations
                case OpCode.ISNULL:
                    WriteLine("let a = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("stack.push(StackItem::Boolean(matches!(a, StackItem::Null)));");
                    break;

                case OpCode.CONVERT:
                    WriteLine("let item = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("let converted = item.convert()?;");
                    WriteLine("stack.push(converted);");
                    break;

                // Exception handling
                case OpCode.THROW:
                    WriteLine("let ex = stack.pop().unwrap_or(StackItem::Null);");
                    WriteLine("return Err(ContractError::UserException(ex.to_string()));");
                    break;

                case OpCode.ASSERT:
                    WriteLine("let cond = stack.pop().unwrap_or(StackItem::Null).to_bool();");
                    WriteLine("if !cond { return Err(ContractError::AssertionFailed); }");
                    break;

                case OpCode.ABORT:
                    WriteLine("return Err(ContractError::Aborted);");
                    break;

                default:
                    WriteLine($"// TODO: Implement {instruction.OpCode}");
                    WriteLine($"return Err(ContractError::UnsupportedOpcode(\"{instruction.OpCode}\"));");
                    break;
            }
        }

        private void PushInteger(Instruction instruction)
        {
            if (instruction.Operand != null)
            {
                var bigInt = new BigInteger(instruction.Operand);
                WriteLine($"stack.push(StackItem::Integer(BigInt::from_str_radix(\"{bigInt}\", 10).unwrap()));");
            }
            else
            {
                WriteLine("stack.push(StackItem::Integer(BigInt::from(0)));");
            }
        }

        private void PushData(Instruction instruction)
        {
            if (instruction.Operand != null)
            {
                // Skip the length prefix
                int prefixSize = instruction.OpCode switch
                {
                    OpCode.PUSHDATA1 => 1,
                    OpCode.PUSHDATA2 => 2,
                    OpCode.PUSHDATA4 => 4,
                    _ => 0
                };

                var data = instruction.Operand[prefixSize..];
                var hexString = Convert.ToHexString(data);
                WriteLine($"stack.push(StackItem::Buffer(hex::decode(\"{hexString}\").unwrap()));");
            }
        }

        private void Jump(Instruction instruction)
        {
            if (instruction.Target != null && instruction.Target.Instruction != null)
            {
                int targetOffset = instruction.Target.Instruction.Offset;
                if (_offsetLabels.TryGetValue(targetOffset, out string? label))
                {
                    WriteLine($"goto {label};");
                }
            }
        }

        private void ConditionalJump(Instruction instruction, bool jumpIfTrue)
        {
            string condition = jumpIfTrue ? "" : "!";
            WriteLine($"if {condition}stack.pop().unwrap_or(StackItem::Null).to_bool() {{");
            _indentLevel++;

            if (instruction.Target != null && instruction.Target.Instruction != null)
            {
                int targetOffset = instruction.Target.Instruction.Offset;
                if (_offsetLabels.TryGetValue(targetOffset, out string? label))
                {
                    WriteLine($"goto {label};");
                }
            }

            _indentLevel--;
            WriteLine("}");
        }

        private void Call(Instruction instruction)
        {
            // For now, just write a placeholder for method calls
            // In a full implementation, this would map to actual Rust function calls
            WriteLine("// Method call - to be implemented based on target address");
        }

        private void Syscall(Instruction instruction)
        {
            if (instruction.Operand != null)
            {
                uint serviceId = BitConverter.ToUInt32(instruction.Operand);
                WriteLine($"// Syscall {serviceId}");
                WriteLine($"let result = syscall({serviceId}, &mut stack)?;");
                WriteLine("if let Some(item) = result { stack.push(item); }");
            }
        }

        private void WriteFooter()
        {
            WriteLine();
            WriteLine("// Entry point");
            WriteLine("#[no_mangle]");
            WriteLine("pub extern \"C\" fn main() -> i32 {");
            _indentLevel++;
            WriteLine($"match {_contractName}::main() {{");
            _indentLevel++;
            WriteLine("Ok(_) => 0,");
            WriteLine("Err(_) => 1,");
            _indentLevel--;
            WriteLine("}");
            _indentLevel--;
            WriteLine("}");
        }

        private void WriteLine(string line = "")
        {
            if (string.IsNullOrEmpty(line))
            {
                _output.AppendLine();
                return;
            }

            // Don't indent labels
            if (!line.EndsWith(":"))
            {
                _output.Append(new string(' ', _indentLevel * 4));
            }
            _output.AppendLine(line);
        }
    }
}
